### PR TITLE
Add support for phpcs.xml.dist (fixes #93)

### LINKED ISSUE #93: Add support for phpcs.xml.dist files
PHPCS Added `phpcs.xml.dist` file support in https://github.com/squizlabs/PHP_CodeSniffer/issues/583, we might need some changes to match.

### PR DESCRIPTION
**Pull request by jyggen**
Just like CodeSniffer itself the linter prefers `phpcs.xml` over `phpcs.xml.dist` (if both exists). Not really sure whether to put `phpcs.ruleset.xml` before or after `phpcs.xml.dist`, but since it seems like CodeSniffer doesn't even support the `phpcs.ruleset.xml` file I went with leaving it as some kind of legacy fallback after the other two.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Aren't `.dist` files meant to be templates that are copied to the "real" file by the person checking it out? (So any customizations don't show as a changed file in the repo, but the "main" config can still be in the repo)

**Comment by jyggen** [comment]
They are, yes :)

**Comment by Arcanemagus** [comment]
Hmmm, reading your initial description... does CodeSniffer process them? :confused:

**Comment by jyggen** [comment]
I realized I might've been a bit vague. CodeSniffer automatically uses`phpcs.xml` and `phpcs.xml.dist` if they exists in the current folder (using `.xml` before `.xml.dist` if both exists). `phpcs.ruleset.xml` on the other hand is not automatically used by CodeSniffer, but will obviously be used if passed to the standard argument (which this linter will if found). 

Why I started to babble about this initaially was because I don't know which order it makes more sense for the linter to look for them in; `phpcs.xml -> phpcs.xml.dist -> phpcs.ruleset.xml` or `phpcs.xml -> phpcs.ruleset.xml -> phpcs.xml.dist`. My reasoning for choosing the former in this PR is that it in that order tries to load the standardized files before the non-standardized one.

**Comment by Arcanemagus** [comment]
From what I remember `phpcs.ruleset.xml` is a "standard" used by Wordpress developers, at least that's how it was described to me.

If CodeSniffer itself loads this file, regardless of the fact that that makes _no_ sense, then I suppose this plugin ought to try to send it on to it as well.

Thanks for the PR!

**Comment by jyggen** [comment]
Thanks!

**Comment by Arcanemagus** [comment]
Published in v1.3.2 :tada:

**Pull request merged**
