### PR TITLE
Document instructions for windows

### PR DESCRIPTION
**Pull request by steelbrain**
Beep Beep

r? @Arcanemagus

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/linter-phpcs/87)

### CODE REVIEW

**Comment by steelbrain** [comment]
@Arcanemagus Shouldn't we be accepting two configs, one for `php` executable and other for `phpcs` phar or executable path? I feel like this is duct taping and that is permanent solution

**Comment by Arcanemagus** [comment]
Neither of these is correct, the simplest method is to just use `composer` or `pear` to install `phpcs` as they will generate proper wrapper scripts and place them in the path for the user.

**Comment by steelbrain** [comment]
The `phar`s are executable by default on Linux. I didn't know much about windows, Thanks!

**Comment by Arcanemagus** [comment]
Oh if you set the executable extension properly you can get it to work in the command prompt, but node on Windows is pretty broken with respect to that (`.bat` doesn't even work) so I doubt that would work. Plus it's just plain more complex :stuck_out_tongue:.

**Comment by Arcanemagus** [comment]
The `.bat` issue might be fixed in 1.3.0, looks like it's actually currently working for me on the beta channel.

**Comment by steelbrain** [comment]
This `.bat` file works by the way, confirmed by the peep in `#linter`

**Pull request closed without merging**
