### PR TITLE
Filter out filename errors due to a bug in PHPCS

### PR DESCRIPTION
**Pull request by skyrpex**
Solves #60

### CODE REVIEW

**Comment by skyrpex** [comment]
Can anyone confirm this works before merging?

**Comment by steelbrain** [comment]
@Arcanemagus ^

**Comment by Arcanemagus** [comment]
Testing now.

**Comment by Arcanemagus** [comment]
This change doesn't break anything, but I can't reproduce the initial issue it is meant to fix either.

So, I'm not against merging it if it fixes things for others, but I can't verify it's actually working.

**Comment by skyrpex** [comment]
@Arcanemagus, the user @rdebeasi commented in #60 that it fixes it and the other error messages are still showing up as expected.

BTW, I created an issue in the PHPCS repository (see squizlabs/PHP_CodeSniffer#711)

**Comment by Arcanemagus** [comment]
Published :wink:.

**Comment by gsherwood** [comment]
A better way to resolve this is for this Atom plugin to tell PHPCS the filename so that sniffs that check the filename still work correctly. To do that, the first line of the input should be `phpcs_input_file: [file path]`, for example:

```php
phpcs_input_file: /path/to/test.php
<?php
echo 'test';

**Comment by Arcanemagus** [comment]
After looking into this further, it looks like this shouldn't even be an issue in the first place as the current `phpcs` version specifically [doesn't run](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/Files/LowercasedFilenameSniff.php#L54-L56) that check when the input is `STDIN`. (Which would explain why I couldn't reproduce the original issue...)

Your suggestion would allow many of the checks that normally disable themselves under `STDIN` to run though, so I'll look into fixing that tonight.

**Comment by Arcanemagus** [comment]
Ha, or not, just looked at the `phpcs` bug report and you are the one that just put that code in there, so I still don't know why I couldn't reproduce it.

I'll be putting the suggested file name hint in there tonight still though.

**Comment by gsherwood** [comment]
> Ha, or not, just looked at the phpcs bug report and you are the one that just put that code in there

Yep. I've fixed the bug but it wont be released until the next version comes out. If you can put the filename line into the plugin, it will start working with all 2.x version of PHPCS straight away.

**Pull request merged**
