### PR TITLE
Add configurable option for which file extensions to include

### PR DESCRIPTION
**Pull request by theteknocat**
When using phpcs in some projects, such as Drupal, it has PHP files with other filename extensions, such as .module. Other PHP projects could also have some weird extensions, and it's important to be able to specify the extensions to accommodate that. This change just adds a simple configuration option to be able to do that.

If this change doesn't make sense to anyone, please let me know.

### CODE REVIEW

**Comment by theteknocat** [comment]
Not sure why the two builds failed, had nothing to do with the code changes I made as far as I can tell.

**Comment by UziTech** [comment]
Hi @theteknocat, I am the new maintainer of this repo. Sorry it took so long to get a response.

If you could add a test for this PR I will merge it.

**Comment by theteknocat** [comment]
@UziTech I'd love to, but I don't really know how. Sorry, I've been coding for a very long time, but doing pull requests in Github with tests is not something I'm particularly familiar with. I'd love a helping hand if you want to PM me and advise.

**Comment by UziTech** [comment]
It looks like it is failing for phpcs v1 and v2 do you know when that option was added to phpcs?

**Pull request merged**
