### PR TITLE
fix underlined error when using tabs

### LINKED ISSUE #146: Wrong column when using tabs
The range for the errors is set as
```
startPoint = [message.line - 1, message.column - 1]
endPoint = [message.line - 1, message.column]
```

The second element is set as the column of the error but the range thinks it is the character of the line.

When using tabs the column of a line is not the same as the character.

image

The `t` is underlined because it is the 3rd character of the line but the `"` should have been underlined as it is in the 3rd column

### PR DESCRIPTION
**Pull request by UziTech**
message.column is the screen column but linter thinks we are returning the buffer column. We need to get the screen row before we get the buffer column incase they have any code folded then we get the buffer position from the screen position.

fixes #146

### CODE REVIEW

**Comment by Arcanemagus** [comment]
This should actually just all be replaced with a call to `helpers.rangeFromLineNumber(textEditor, message.line - 1, message.column - 1)`.

As for the odd highlighting you were seeing in #146, are you sure that `phpcs` isn't reporting the wrong column? If you are using tabs instead of spaces I've seen it do some pretty bizarre things (like converting them to _x_ spaces for character counts instead of properly counting them as 1 character).

**Comment by UziTech** [comment]
`helpers.rangeFromLineNumber(textEditor, message.line - 1, message.column - 1)` sets the range from `message.column - 1` to the end of the line which I don't believe is correct for some errors. Underlining just one character is a better solution when the full range is not known IMO. That way it is less likely to have overlapping underlines.

`message.column` that phpcs returns is the column of the document that the error occurred on. My pull request changes that value to the buffer column that linter is expecting.

**Comment by Arcanemagus** [comment]
`phpcs` only gives us a single column, it's not correct, but it's far more visible than the single character currently being shown. Most other linters have already switched to that, I just haven't had a chance to update this linter yet.

I'm not sure where you have gotten confused with the columns here, `linter` expects the range given to it to be the column in the text content. This means the character count from the start of the line is the column, in a 0 index fashion. As I said before, when you are using tabs I've seen `phpcs` report the wrong column, which I'm sure is what you were seeing in #146.

**Comment by UziTech** [comment]
Yes with the --tab-with parameter set it [replaces tabs with spaces](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Advanced-Usage#replacing-tabs-with-spaces) before checking the document which means the column that is returned by `phpcs` is the [screen column](https://atom.io/docs/api/v1.4.0/TextEditor#buffer-vs-screen-coordinates) not the buffer column (or character count from the start of the line)

This pull request is to change the column that `phpcs` returns into the buffer column, which is what `linter` is expecting.

Are you saying this is an error in `phpcs` and should be fixed in their code?

**Comment by Arcanemagus** [comment]
I'd say it's an error in user configuration. Tabs can be set to any width, which causes all sorts of interoperability issues, and is the primary reason (as far as I see) why they should be avoided.

In this case your proposed "fix" would only work if you have Atom and `phpcs` both set to do the same conversion for tabs, which is _not_ a guarantee, or even a good assumption.

**Comment by Arcanemagus** [comment]
You could also say that this is an issue with the design of `phpcs` that that is even an option, but that's another discussion :stuck_out_tongue:.

**Comment by UziTech** [comment]
I would say it is a pretty good assumption that the tab width of `phpcs` is set the same as `atom` since `linter-phpcs` has a [tab width setting](https://github.com/AtomLinter/linter-phpcs/blob/master/lib/main.coffee#L38) that sets the --tab-width parameter of `phpcs`

**Comment by UziTech** [comment]
this will be fixed by a pull request to PHPCS 

https://github.com/squizlabs/PHP_CodeSniffer/pull/998

**Pull request closed without merging**
